### ISSUE TITLE
ParseFiles函数解析案例中的index.html文件，执行html页面后显示异常，页面丢失，在页面上查看源码也是被截断的状态

### ISSUE THREAD

**Issue by Daytoyy** [L1ng14/bookstore#1]
以下是部分代码
func IndexHandler(w http.ResponseWriter,r *http.Request){
	  t:=template.Must(template.ParseFiles("views/index.html"))
	  t.Execute(w,"")
}

func main(){
	  http.Handle("/static/",http.StripPrefix("/static/",http.FileServer(http.Dir("views/static/"))))	
	  http.Handle("/pages/",http.StripPrefix("/pages/",http.FileServer(http.Dir("views/pages/"))))
	  http.HandleFunc("/main",IndexHandler)
	  http.ListenAndServe(":8080",nil)
}
在页面上显示异常如下所示：
![image](https://user-images.githubusercontent.com/84886371/119756976-dde54100-bed6-11eb-882f-0012ca303b8f.png)

源码所示：
![image](https://user-images.githubusercontent.com/84886371/119757042-f81f1f00-bed6-11eb-8318-39de2bc3130e.png)

**Comment by L1ng14** [comment]
这种情况一般模板引擎解析出错导致的
---
![图片](https://user-images.githubusercontent.com/53606022/119760747-1ee05400-bedd-11eb-9747-ba3ca9c54fcd.png)

上面是我的模板，红线以下是你提到的没有解析出来的地方，你可以查看你传给模板的对象是否有这个变量，没有的话，修改你的`Go`代码了。

**Comment by Daytoyy** [comment]
> ## 这种情况一般模板引擎解析出错导致的
> ![图片](https://user-images.githubusercontent.com/53606022/119760747-1ee05400-bedd-11eb-9747-ba3ca9c54fcd.png)
> 
> 上面是我的模板，红线以下是你提到的没有解析出来的地方，你可以查看你传给模板的对象是否有这个变量，没有的话，修改你的`Go`代码了。

感谢，刚学了新内容，找到问题了

**Comment by Daytoyy** [comment]
> ## 这种情况一般模板引擎解析出错导致的
> ![图片](https://user-images.githubusercontent.com/53606022/119760747-1ee05400-bedd-11eb-9747-ba3ca9c54fcd.png)
> 
> 上面是我的模板，红线以下是你提到的没有解析出来的地方，你可以查看你传给模板的对象是否有这个变量，没有的话，修改你的`Go`代码了。

感谢，刚学了新内容，找到问题了

**Comment by L1ng14** [comment]
:ok:
