### ISSUE TITLE
code里是不是缺包，直接clone不能运行

### ISSUE THREAD

**Issue by rainbows1122** [l1ng14/bookstore#4]
bookstores2/src/controller

**Comment by l1ng14** [comment]
发出你的报错，少年。

**Comment by l1ng14** [comment]
> bookstores2/src/controller

发出你的报错，少年。 @rainbows1122

**Comment by l1ng14** [comment]
Rename all packages
```
 bookstores2/src/*
```
to
```
bookstores2/*
```

**Comment by rainbows1122** [comment]
![image](https://user-images.githubusercontent.com/758105/132426551-dd3cfdcf-5dda-40f7-b681-eb50160af811.png)

**Comment by rainbows1122** [comment]
package main: 
main.go:4:2: invalid import path: "bookstores2/*"

**Comment by l1ng14** [comment]
> package main:
> main.go:4:2: invalid import path: "bookstores2/*"

@rainbows1122 建议先了解 `package` 相关知识 https://golang.org/doc/code#ImportingLocal
稍后我会进行修复。

**Comment by l1ng14** [comment]
> package main:
> main.go:4:2: invalid import path: "bookstores2/*"

 @rainbows1122  已修复。 https://github.com/l1ng14/bookstore/commit/7052c20b8b970190dcff64bd5527dd2a36a2a6d3.
